image:
  name: docker/compose:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker-compose -f compose.yml build

deploy-on-test:
  stage: deploy
  script:
    - docker-compose -f compose.yml --project-name night-city-rp-test --env-file test.env down
    - docker-compose -f compose.yml --project-name night-city-rp-test --env-file test.env up -d
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-on-prod:
  stage: deploy
  script:
    - docker-compose -f compose.yml --project-name night-city-rp-prod --env-file prod.env down
    - docker-compose -f compose.yml --project-name night-city-rp-prod --env-file prod.env up -d
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
