image:
  name: docker/compose:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "hello, kitty!"

deploy:
  stage: deploy
  script:
    - echo "deployed!"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
