image:
  name: docker/compose:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker-compose -f compose.yml build

deploy:
  stage: deploy
  script:
    - docker-compose -f compose.yml down
    - docker-compose -f compose.yml up -d
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
