image:
  name: docker/compose:latest

stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3-eclipse-temurin-17
  script:
    - cd backend
    - mvn package -DskipTests --no-transfer-progress
    - cp target/backend-*.jar target/app.jar
  artifacts:
    paths:
      - backend/target/app.jar

test:
  stage: build
  image: maven:3-eclipse-temurin-17
  script:
    - cd backend
    - mvn test --no-transfer-progress

system-test:
  stage: build
  image: nexus-public-docker-repo.ntrubkin.ru/ntrubkin/java-maven-docker:21
  rules:
    - when: manual
  before_script:
    - docker-compose -f compose-ci-cd.yml --project-name night-city-rp-ci-cd build
    - docker-compose -f compose-ci-cd.yml --project-name night-city-rp-ci-cd down
    - docker-compose -f compose-ci-cd.yml --project-name night-city-rp-ci-cd up -d
    - cp tests/src/main/resources/application-ci-cd.yml tests/src/main/resources/application.yml
    - cp tests/src/main/resources/jooq-config-ci-cd.xml tests/src/main/resources/jooq-config.xml
  script:
    - cd tests
    - docker run --rm $(docker build -f ci-cd-dockerfile -q .)
    - echo $?
  after_script:
    - docker-compose -f compose-ci-cd.yml --project-name night-city-rp-ci-cd down -v
  needs:
    - job: build
      artifacts: true
  allow_failure: true

checkstyle:
  stage: build
  image: maven:3-eclipse-temurin-17
  script:
    - cd backend
    - mvn checkstyle:check --no-transfer-progress

deploy-on-test:
  stage: deploy
  script:
    - docker-compose -f compose-test.yml --project-name night-city-rp-test build
    - docker-compose -f compose-test.yml --project-name night-city-rp-test down
    - docker-compose -f compose-test.yml --project-name night-city-rp-test up -d
  rules:
    - when: manual
  needs:
    - job: build
      artifacts: true
  allow_failure: true

deploy-on-prod:
  stage: deploy
  script:
    - docker-compose -f compose-prod.yml --project-name night-city-rp-prod build
    - docker-compose -f compose-prod.yml --project-name night-city-rp-prod down
    - docker-compose -f compose-prod.yml --project-name night-city-rp-prod up -d
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  needs:
    - job: build
      artifacts: true
  allow_failure: true
