version: '3.6'

services:
  night-city-rp-backend:
    image: night-city-rp-backend:latest
    build:
      context: backend/
    restart:
      unless-stopped
    ports:
      - "10037:8080"
    environment:
      - app.enable-cors=false
      - spring.profiles.active=json-logging
      - spring.datasource.url=jdbc:postgresql://night-city-rp-db:5432/night_city_rp
      - spring.datasource.username=night-city-rp
      - spring.datasource.password=postgres
      - spring.main.banner-mode=off
    depends_on:
      - night-city-rp-db
    networks:
      - night-city-rp-system-tests
      - apps_default

  night-city-rp-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=night_city_rp
      - POSTGRES_USER=night-city-rp
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    ports:
      - "10038:5432"
    restart: unless-stopped
    networks:
      - night-city-rp-system-tests
      - apps_default

  night-city-rp-frontend:
    image: night-city-rp-frontend:latest
    build:
      context: frontend/
    ports:
      - "10039:5432"
    restart:
      unless-stopped
    networks:
      - night-city-rp-system-tests
      - apps_default

networks:
  night-city-rp-system-tests:
  apps_default:
    external: true