version: '3.6'

services:
  night-city-rp-backend:
    image: night-city-rp-backend:latest
    build:
      context: backend/
    networks:
      - night-city-rp
    restart:
      unless-stopped
    environment:
      - app.enable-cors=false
      - spring.profiles.active=json-logging
      - spring.datasource.url=jdbc:postgresql://night-city-rp-db:5432/night_city_rp
      - spring.datasource.username=${TEST_POSTGRES_USERNAME}
      - spring.datasource.password=${TEST_POSTGRES_PASSWORD}
      - spring.main.banner-mode=off
    depends_on:
      - night-city-rp-db
    ports:
      - "10005:8080"

  night-city-rp-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=night_city_rp
      - POSTGRES_USER=${TEST_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - /mnt/pool-1/night-city-rp-test/db/data/postgres:/data/postgres
    restart: unless-stopped
    networks:
      - night-city-rp
    ports:
      - "10006:5432"

  night-city-rp-frontend:
    image: night-city-rp-frontend:latest
    build:
      context: frontend/
    hostname: night-city-rp-frontend-test
    networks:
      - night-city-rp
      - apps_default
    restart:
      unless-stopped
    ports:
      - "10007:80"

networks:
  night-city-rp:
  apps_default:
    external: true
