version: '3.6'

services:
  night-city-rp-backend:
    image: night-city-rp-backend:latest
    build:
      context: backend/
    networks:
      - night-city-rp
    restart:
      unless-stopped
    environment:
      - spring.datasource.url=jdbc:postgresql://night-city-rp-db:5432/night-city-rp
      - spring.datasource.username=night-city-rp
      - spring.datasource.password=postgres          # todo: сменить и спрятать в секреты
      - app.enable-cors=false
    depends_on:
      - night-city-rp-db
    ports:
      - "${BACKEND_PORT}:8080"

  night-city-rp-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=night-city-rp
      - POSTGRES_USER=night-city-rp
      - POSTGRES_PASSWORD=postgres    # todo: сменить и спрятать в секреты
      - PGDATA=/data/postgres
    volumes:
      - /mnt/pool-1/night-city-rp/db/data/postgres:/data/postgres
    restart: unless-stopped
    networks:
      - night-city-rp
    ports:
      - "${DB_PORT}:5432"

  night-city-rp-frontend:
    image: night-city-rp-frontend:latest
    build:
      context: frontend/
    hostname: night-city-rp-frontend-${ENV_NAME}
    networks:
      - night-city-rp
      - apps_default
    restart:
      unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"

networks:
  night-city-rp:
  apps_default:
    external: true
