version: '3.6'

services:
  night-city-rp-backend:
    image: night-city-rp-backend:latest
    build:
      context: backend/
    networks:
      - night-city-rp
    restart:
      unless-stopped
    environment:
      - app.enable-cors=false
      - spring.profiles.active=json-logging
      - spring.datasource.url=jdbc:postgresql://night-city-rp-db:5432/night-city-rp
      - spring.datasource.username=night-city-rp
      - spring.datasource.password=postgres          # todo: сменить и спрятать в секреты
      - springdoc.api-docs.enabled=false
      - springdoc.swagger-ui.enabled=false
    depends_on:
      - night-city-rp-db
    ports:
      - "10014:8080"

  night-city-rp-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=night-city-rp
      - POSTGRES_USER=night-city-rp
      - POSTGRES_PASSWORD=postgres    # todo: сменить и спрятать в секреты
      - PGDATA=/data/postgres
    volumes:
      - /mnt/pool-1/night-city-rp-prod/db/data/postgres:/data/postgres
    restart: unless-stopped
    networks:
      - night-city-rp
    ports:
      - "10015:5432"

  night-city-rp-frontend:
    image: night-city-rp-frontend:latest
    build:
      context: frontend/
    hostname: night-city-rp-frontend-prod
    networks:
      - night-city-rp
      - apps_default
    restart:
      unless-stopped
    ports:
      - "10016:80"

networks:
  night-city-rp:
  apps_default:
    external: true
