name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.ntrubkin.ru/ntrubkin/night-city-rp"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "true"
          GITLAB_HOSTNAME: "gitlab.ntrubkin.ru"
          GITLAB_USERNAME: "ntrubkin"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "62"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

